spring.datasource.url= jdbc:postgresql://postgres:5432/experiences-config
spring.datasource.username= postgres
spring.datasource.password= /Sanji33
spring.datasource.hikari.auto-commit=false
spring.transaction.rollback-on-commit-failure=true

# spring JPA
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update

# serialization
spring.jackson.serialization.fail-on-empty-beans=false


# web config
spring:
    web:
        cors:
            allow-credentials: true
            allowed-origins: "http://localhost:4200"
            allowed-methods: GET,POST,PUT,DELETE,OPTIONS
            allowed-headers: "*"
