version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /Sanji33
      POSTGRES_DB: experiences-config
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: ./ExperiencesConfigurationBackendImage
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}  # Defaults to 1000 if not set in environment
        GID: ${GID:-1000}  # Defaults to 1000 if not set in environment
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./ExperiencesConfigurationBackendCode:/home/user/app
      - ../config_files:/home/user/config_files
      - ~/.m2:/home/user/.m2

  angular-frontend:
    build:
      context: ./ExperiencesConfigurationTemplateImage
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1010}
        GID: ${GID:-1010}
    ports:
      - "4200:4200"
    depends_on:
      - springboot-app
    volumes:
      - ./ExperiencesConfigurationTemplateCode:/home/node/app

volumes:
  postgres-data:
